### ISSUE TITLE
The distgit-bugzilla-sync script needs to be updated to use FASJSON

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fasjson#100]
Code lives at: https://pagure.io/fedora-infra/distgit-bugzilla-sync/

It uses:
- people_by_key
- group_by_name
- person_by_username

https://pagure.io/fedora-infra/distgit-bugzilla-sync/blob/master/f/distgit_bugzilla_sync/script.py

**Comment by pypingou** [comment]
This is being ported to toddlers, so the work will more likely happen over there

**Comment by ryanlerch** [comment]
@pypingou so can we close this one here then?

**Comment by pypingou** [comment]
Probably not, we could just open a ticket for toddler and close this one :)

**Comment by pypingou** [comment]
Note that this is still needs to be ported to toddlers

**Comment by StephenCoady** [comment]
@pypingou do we need both this and #99? to me they look the same since the script is contained in the plugin in toddlers now.

**Comment by pypingou** [comment]
It has been ported to toddlers yes, so we can drop this ticket.

I still need to deploy that toddler, but I should be able to do it before noggin is deployed :)

**Comment by StephenCoady** [comment]
OK great thanks. I will take a look at porting the code now.
