### ISSUE TITLE
As a developer, I want a consistent way to handle API responses

### ISSUE THREAD

**Issue by odra** [fedora-infra/fasjson#12]
Related Issue: #7 

Example

```py
from flask import Flask, Response

#subclasses the default flask.Response object
class AppResponse(Response):
	charset = 'utf-8'
	default_status = 200
	default_mimetype = 'application/json'

	@classmethod
	def from_result(cls, status_code, data=None):
		instance = cls(status=status_code)
		if data:
			instance.data = {
				'result': data
			}
		return instance

	@classmethod
	def from_error(cls, e):
		instance = cls(status=e.status_code)
		instance.data = json.dumps({
			'error': e.as_dict()
		})
		return instance

	@classmethod
	def force_type(cls, rv, environ=None):
		#forces json parsing for all responses
		if type(rv) != str:
			rv = json.dumps(rv)
		return super(AppResponse, cls).force_type(rv, environ)


app = Flask(__name__)
app.response_class = AppResponse


@app.route('/1')
def one():
	return AppResponse.from_result(status_code=200, data={'a': 1})

@app.route('/2')
def two():
	#works since the respone class is able to parse objects to jsonstring
	return {'a': 1}
``` 

## Acceptance Criteria

* A response class that inherits from `flask.Response`
* A class that dumps objects into json strings with helper methods for  `result` or `error` responses
* The class should be set as the response class for the flask app object

## Definition of Done

The class being used as the flask response class.

**Comment by abompard** [comment]
I think I would also be OK if you found a popular and well-maintained REST library for Flask that suits you.

Also I think the class (or library) we end up using should handle versionned APIs without making us write the code twice (something based on inheritance or having the version around in the method to do conditionals would be nice).

**Comment by odra** [comment]
I took a look at some of them, I didn't see much value in using those framework but to those some libraries within flask itself such as https://flask-marshmallow.readthedocs.io/en/latest/ for data serialization for example.

About API versioning, I think flask blueprints would fit our needs since they provide a way to attach flask apps within flask apps with url prefix per app and etc.
