### ISSUE TITLE
Since IPA STG was reinstalled, fasjson doesn't return all group members

### ISSUE THREAD

**Issue by arrfab** [fedora-infra/fasjson#140]
Something that was working before the IPA STG reinstall and that doesn't work anymore : 
When querying fasjson stg for group members, fasjson returns only 10 members while the group in IPA has more than that.
Calling fasjson with requests like `/v1/groups/%s/members/?page_size=1000` doesn't even return all users, and the returned json by fasjson only has 10 items and also shows this : `u'page': {u'total_results': 10, u'total_pages': 1, u'page_number': 1, u'page_size': 1000}} ` so still only returning 10 results .
Is there a new limitation in fasjson or is that an issue in the new/fresh IPA instance that doesn't allow returning more than 10 items ?

**Comment by arrfab** [comment]
FWIW, the group I'm querying is `centosproject-email-aliases`

**Comment by StephenCoady** [comment]
@arrfab @abompard I can take a look at this, but I've tried to reproduce and don't seem to be able to. Can you confirm the same?

I'm currently getting `{'total_results': 97, 'page_size': 1000, 'page_number': 1, 'total_pages': 1}`

**Comment by arrfab** [comment]
Yes, I confirm 97 here too (automatically generated through script), and it was due to the memberOf issue that @abompard was working on .. can have a look at real number to see if it's all there, or still some are missing.
So issue wasn't in fasjson, but directly in IPA (as discussed in the last days on irc)

**Comment by StephenCoady** [comment]
Ah, I somehow didn't make the connection. I was going to close but I'll leave @abompard repurpose the ticket then since he has done work on it. Thanks!

**Comment by arrfab** [comment]
Let me close this one, as it seems now resolved
