### ISSUE TITLE
As a user, I want to query more object fields in the list_* endpoints

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fasjson#144]
@arrfab has a script that builds the mail aliases from the members of a group. For that, he needs to query fasjson's `list_group_member` endpoint which returns a list of usernames. Then he has to query each username in turn to get their email address. This makes a lot of requests, periodically run every 10 minutes or so.

We could use [field masks](https://flask-restx.readthedocs.io/en/latest/mask.html) to allow clients to request additional object attributes in the `list_*` endpoints (and in other endpoints too, why not). This will allow Fabian's script to make a single query.

## Acceptance Criteria

* Client can request object attributes using field masks
* Fasjson honors field masks and filters out or adds this fields to the ldap query, returning them as appropriate to the client
* The `list_*` endpoints and optionnaly the `get_*` endpoints handle field masks

## Definition of Done

* AC are met
* 100% code coverage
* Documentation is updated

**Comment by arrfab** [comment]
For reference, that's what I pushed to centos infra to build aliases for postfix (through virtusertable) : 
https://github.com/CentOS/ansible-role-postfix/blob/master/templates/gen-virtusertable-from-fasjson.j2

So yes, asking member and then parsing result, and query for each user details to retrieve email
