### ISSUE TITLE
RFE: Support for retrieving a user's SSH public key(s)

### ISSUE THREAD

**Issue by sgallagher** [fedora-infra/fasjson#186]
## Acceptance Criteria

* fasjson includes the SSH public key(s) of a user, ideally in the format expected by openssh's `authorized_keys` file.

## Definition of Done
The deployed, production version of fasjson in the Fedora Project includes this information.

**Comment by sgallagher** [comment]
For further context: I want to develop a plugin for Anaconda to allow users to authenticate to FAS during the installation process and deploy their new system with SSH keys for remote access.

**Comment by nirik** [comment]
FWIW, I'd be fine if this did not require auth. :) Just get a list of ssh keys associated with a list of users.

**Comment by sgallagher** [comment]
Right, there's no need for the fasjson to require auth to retrieve this information.
