### ISSUE TITLE
It's not very easy to hack on fasjson

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fasjson#2]
Hacking on the project is currently a pretty involved thing, one needs a FreeIPA instance separate from the local machine (because FreeIPA automatically registers the host it's installed on as a client), one needs to install things to enable GSSAPI in Apache, etc.

It would be easier if there was a Vagrant setup (or equivalent) that a developer could use to make and test changes to the code.

For a Vagrant setup, the acceptance criteria would be :
- A developer just has to check out the code and run `vagrant up` to have a running VM with the project installed.
- There is no external dependency once the VM is running (no need to have a FreeIPA server installed somewhere)

DoD: all of the above are met.

**Comment by abompard** [comment]
I would say "medium" if we can reuse most of the setup that we have on securitas. The downside is that fasjson and FreeIPA would be installed on the same host, so we won't be testing the GSSProxy setup that is shipped in the `config` folder, nor the client declaration step that is listed in the README, but it would be sufficient to hack on the code and test it.

**Comment by tiran** [comment]
You cannot have fasjson in the same Apache instance as IPA API server. The services have conflicting configuration.

You could also use containers here. It's possible to run IPA server in a container (root container, podman doesn't currently work for me).

**Comment by abompard** [comment]
> You cannot have fasjson in the same Apache instance as IPA API server. The services have conflicting configuration.

Thanks for the advice!

> You could also use containers here. It's possible to run IPA server in a container (root container, podman doesn't currently work for me).

Yeah that was my plan B: make a Vagrant instance that would run the fasjson code in it's Apache instance and also run the FreeIPA docker image.
