### ISSUE TITLE
Return the `fasrhbzemail` attribute of users

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fasjson#288]
## Acceptance Criteria

* The `fasRHBZEmail` attribute value is returned when the user has set it

## Definition of Done

* AC is met
* Unit tests pass with 100% coverage
* Docs are updated

**Comment by phsmoura** [comment]
Hi @abompard, I'd like to work on that one, can I do it?

**Comment by abompard** [comment]
Hi! Actually @humaton had expressed his interest in working on this, sorry! But there are plenty of other issues tagged with "Good First Issue" if you're looking for inspiration :-)

**Comment by abompard** [comment]
(hmm actually not on FASJSON, but in [Noggin](https://github.com/fedora-infra/noggin/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) there is :-) )

**Comment by abompard** [comment]
Oh, I see you've talked to him in a meeting already, then it's all good, go for it!
I'm here if you have any question on the dev environment or on what needs to be done.
