### ISSUE TITLE
Continuous deployment of fasjson in CommuniShift

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fasjson#3]
As a developer, I'd like to have fasjson deployed alongside securitas in CommuniShift, in a CD manner.

It may be more complex than securitas because fasjson uses Kerberos / GSSAPI to authenticate.

Acceptance criteria:
- fasjson is deployed in CommuniShift
- the instance updates when code changes happen in fasjson
- it is linked to the same FreeIPA server as securitas

DoD: all of the above are met.

**Comment by sfinn85** [comment]
Hi @abompard 
What is the external action , we are waiting on here?

**Comment by abompard** [comment]
The same as [securitas#64](https://github.com/fedora-infra/securitas/issues/64) which got unblocked, so this should be good to work on.

**Comment by sfinn85** [comment]
Downtime for Communishift approx 3 weeks

**Comment by abompard** [comment]
It's working!
```
curl --negotiate -u : http://fasjson-noggin.the-new-private-place/v1/groups
{"result":{"data":["admins","ipausers","editors","trust admins","mohans-group"],"size":0}}
```
