### ISSUE TITLE
API spec endpoint

### ISSUE THREAD

**Issue by odra** [fedora-infra/fasjson#31]
As a developer, I want an API endpoint to retrieve the open-api specification in JSON format.

## Acceptance Criteria

* GET endpoint in /v1/
* Should return the specification content from the specs folder
* The `specs` folder should be included in the project distribution
* Should this endpoint be public (no authentication required)?

## Definition of Done

Retrieve the project's open-api spec definition in a GET HTTP request.

**Comment by abompard** [comment]
I think this endpoint should be public, so clients can get the spec and configure themselves before having to authenticate.

**Comment by odra** [comment]
I thought so to, it will require a change in how the app handles authentication, it validates it for all API paths ATM - I think it could use some kind of "white_list' to list paths/path patterns that are allowed to be executed without any kind of authentication.

**Comment by abompard** [comment]
This was done in #73

**Comment by StephenCoady** [comment]
Yep, pinged you on chat today about it about re-assigning and closing.
