### ISSUE TITLE
As a developer I would like a migration guide so that it is easy for me to know which method to use in fasjson_client

### ISSUE THREAD

**Issue by StephenCoady** [fedora-infra/fasjson#52]
We should provide a migration guide to allow developers easily identify which methods in the fasjson-client they will use instead of the method they are currently using in python-fedora.

The majority of apps use the following calls:

```
person_by_username
group_by_name
person_by_id
"/user/list"
```

PR here: https://github.com/fedora-infra/fasjson-client/pull/14

**Comment by StephenCoady** [comment]
Applications which rely on python-fedora:

```
hubs
badges
datanomer
fedmsg_meta_fedora_infrastructure
fmn
pdc
sigul
fedmsg-genacls
elections
pkdb2
supybot-fedora
fedscm-admin
```

I will create issues for each of these to track them being updated when python-fedora is updated.

**Comment by nirik** [comment]
The following are dead and can be removed from your list: 

hubs
fedmsg-genacls (I think this is now part of pagure or pagure-over-dist-git)
pkgdb2

The following will be going away someday, but still exist for now: 
fedmsg_meta_fedora_infrastructure
fmn
pdc

**Comment by StephenCoady** [comment]
thats great, thanks @nirik - will update. Are any of the other apps from this project's wiki jumping out at you as obselete?

**Comment by mattiaverga** [comment]
bodhi-client relies on python-fedora
