### ISSUE TITLE
Is it possible to query who sponsored user into group and when?

### ISSUE THREAD

**Issue by FrostyX** [fedora-infra/fasjson#522]
Previously, when using the `python-fedora` package, I was able to query group members and see who sponsored them and when. The code I used looked something like this:

```python
from fedora.client import AccountSystem

client = AccountSystem()

packager_group = client.group_by_name("packager")
for role in packager_group.approved_roles:
    if role.role_type != 'user':
        continue

    print(role.approval)
    print(role.sponsor_id)
    print(role.person_id)
```

I suppose it is not possible to query such information with the current version of `fasjson`? Do you have such information in the database, or there is no way to implement this?

**Comment by abompard** [comment]
Unfortunately that information is not stored in IPA (LDAP). We may be able to add it, but it would be a pretty significant chunk of work I think.

**Comment by FrostyX** [comment]
Ah, that's a pity. Thank you @abompard.
