### ISSUE TITLE
LDAP queries are not bound as the connecting user

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fasjson#55]
LDAP queries are not bound as the connecting user but with the host's keytab.

```
$ klist -A
Ticket cache: KCM:1000
Default principal: admin@EXAMPLE.TEST
Valid starting       Expires              Service principal
04/23/2020 09:40:04  04/24/2020 09:39:53  HTTP/fasjson.example.test@EXAMPLE.TEST
04/23/2020 09:39:58  04/24/2020 09:39:53  krbtgt/EXAMPLE.TEST@EXAMPLE.TEST
04/23/2020 10:14:04  04/24/2020 09:39:53  HTTP/ipa.example.test@EXAMPLE.TEST
04/23/2020 13:13:05  04/24/2020 09:39:53  ldap/ipa.example.test@EXAMPLE.TEST
$ curl --negotiate -u : http://fasjson.example.test/fasjson/v1/me
{"result":{"info":{"cn":["services","accounts"],"dc":["example","test"],"krbprincipalname":"http/fasjson.example.test@example.test"},"raw":"dn: krbprincipalname=http/fasjson.example.test@example.test,cn=services,cn=accounts,dc=example,dc=test"}}
```

FASJSON should return the DN of `admin@EXAMPLE.TEST` and not the service.
Apache's mod_wsgi shows `admin@EXAMPLE.TEST` in the log files and sets `GSS_NAME` to that value as well. It also sets `KRB5CCNAME` to `FILE:/run/fasjson/ccaches/admin@EXAMPLE.TEST` in the request's environment.

The bind is done with:
```
self.conn.sasl_interactive_bind_s(
    "", ldap.sasl.sasl({}, "GSS-SPNEGO")
)
```

@tiran any idea what is going on?

**Comment by abompard** [comment]
Progress! The `KRB5CCNAME` environment variable that Apache set was the *request* environment, not the *process* environment. I've set `os.environ["KRB5CCNAME"] = request.environ["KRB5CCNAME"]` and now I have a different error message:
```
GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Credential cache is empty)
```

The file is definitely not empty but something seems odd:
```
# klist /run/fasjson/ccaches/admin@EXAMPLE.TEST     
Ticket cache: FILE:/run/fasjson/ccaches/admin@EXAMPLE.TEST                        
Default principal: admin@EXAMPLE.TEST             
Valid starting       Expires              Service principal                
01/01/1970 00:00:00  01/01/1970 00:00:00  Encrypted/Credentials/v1@X-GSSPROXY:
```

Could it be related to GSSProxy?

**Comment by tiran** [comment]
@simo @frozencemetery please assist

**Comment by abompard** [comment]
I can reproduce the error with this very simple wsgi app:

```python
import os
import ldap
from flask import Flask, request
app = Flask(__name__)

@app.before_request
def set_environ():
    os.environ["KRB5CCNAME"] = request.environ["KRB5CCNAME"]

@app.route("/")
def root():
    ldap.set_option(ldap.OPT_REFERRALS, 0)
    conn = ldap.initialize("ldap://ipa.example.test", trace_level=2)
    conn.protocol_version = 3
    SASL_GSSAPI = ldap.sasl.sasl({}, "GSSAPI")
    conn.sasl_interactive_bind_s("", SASL_GSSAPI)
    dn = conn.whoami_s()
    return dn + "\n"

application = app
```

**Comment by abompard** [comment]
And this is my Apache config file:
```
WSGISocketPrefix /run/httpd/wsgi
WSGIPythonHome /srv/venv
WSGIDaemonProcess fasjson processes=4 threads=1 maximum-requests=500 \
  display-name=%{GROUP} socket-timeout=2147483647 \
  lang=C.UTF-8 locale=C.UTF-8
WSGIScriptAlias /fasjson2 /vagrant/testgssapi.py
WSGIScriptReloading Off
WSGIRestrictStdout Off
WSGIRestrictSignal Off

<Location "/fasjson2">
  AuthType GSSAPI
  AuthName "Kerberos Login"
  GssapiUseSessions On
  Session On
  SessionCookieName ipa_session path=/fasjson;httponly;secure;
  SessionHeader IPASESSION
  GssapiSessionKey file:/run/fasjson/session.key
  GssapiImpersonate On
  GssapiDelegCcacheDir /run/fasjson/ccaches
  GssapiDelegCcachePerms mode:0660
  GssapiUseS4U2Proxy On
  GssapiAllowedMech krb5

  Require valid-user
  WSGIProcessGroup fasjson
  WSGIApplicationGroup fasjson
  Header always append X-Frame-Options DENY
  Header always append Content-Security-Policy "frame-ancestors 'none'"
  Header unset Set-Cookie
  Header unset ETag
  FileETag None
</Location>
```

**Comment by abompard** [comment]
Hey folks, I'd really love to have some help with this, I don't know where to look for this issue. I have started reading on Kerberos delegation in `mod_wsgi` and testing things but it's not going anywhere. If you had any directions to point me to I would be very grateful.

**Comment by tiran** [comment]
I think it's missing the s4u2proxy service delegation flag. We can re-use the ``ipa-ldap-delegation-targets`` target that contains all IPA server LDAP principals. Please give this a try:

```
ipa servicedelegationrule-add fasjson-delegation
ipa servicedelegationrule-add-member --principals=HTTP/fasjson.ipa.example fasjson-delegation
ipa servicedelegationrule-add-target --servicedelegationtargets=ipa-ldap-delegation-targets fasjson-delegation
```

**Comment by abbra** [comment]
Remember that Kerberos (or GSSAPI with krb5 mechanism) authentication is not transitive. You as a user authenticate to the service. The service cannot on its own to turn to other service and act on your behalf. It has to be allowed to do so by the KDC. This is called 'Services for Users' extensions (S4U) and there are two of those:
 - S4U2Proxy, where a user authenticates to a service, then service obtains a ticket to a different service on behalf of this user, effectively impersonating the user. This is your use case.
 - S4U2Self, where a user authenticates to a service using non-Kerberos authentication (certificate auth or anything else that is not really based on the Kerberos itself), then says to KDC that it verified the user credentials and asks for a service ticket to itself on behalf of the user.

S4U2Proxy is how we set up FreeIPA framework's IPA-API server endpoint. We pre-define in KDC that `HTTP/master.ipa.test` service can use S4U2Proxy on behalf of the user to talk to other specific services (`ldap/master.ipa.test` and `cifs/master.ipa.test`). That is what you need to define here: what services your FAS service has to talk to and how, with `ipa help servicedelegationrule` set of commands.
See `ipatests/test_xmlrpc/test_servicedelegation_plugin.py` in IPA test suite for details of using it. For deeper explanation see my blog from 2013: https://vda.li/en/posts/2013/07/29/Setting-up-S4U2Proxy-with-FreeIPA/, before we added `ipa servicedelegationrule-*` commands.

**Comment by abompard** [comment]
Thanks a lot for your help, I'm going to test that right away. I didn't realize service delegation had to be enabled per-service in IPA. Just running the 3 commands was not sufficient, @tiran pointed me that the gssproxy configuration was missing the `allow_constrained_delegation = true` line.

This is now working! I owe you all a few beverages of your choice whenever we're allowed to meet people again :-)

**Comment by abbra** [comment]
you're welcome. GSS-Proxy did not exist when all this was written. ;)
