### ISSUE TITLE
fedmsg_meta_fedora_infrastructure needs to be updated to use the new API

### ISSUE THREAD

**Issue by StephenCoady** [fedora-infra/fasjson#58]
See: https://github.com/fedora-infra/fasjson/issues/52

https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/fedmsg_meta_fedora_infrastructure/fasshim.py it uses python-fedora to hit '/user/list'

**Comment by StephenCoady** [comment]
PR is here: https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/pull/503

**Comment by nphilipp** [comment]
I've checked the upstream PR and there were no outstanding requests for change (marked the outdated conversations as resolved). I've rebased the PR onto latest HEAD.

**Comment by nphilipp** [comment]
Found that this needs to work with Python 2.7, added a fasjson-client shim (because that one only works on Python >= 3.6), debugging CI failures.
