### ISSUE TITLE
elections needs to be updated to use the new API

### ISSUE THREAD

**Issue by StephenCoady** [fedora-infra/fasjson#62]
elections sets up python-fedora here: https://pagure.io/elections/blob/develop/f/fedora_elections/__init__.py#_68 

and uses it to make a few calls (mostly person_by_username) throughout the app.

This should be changed to use fasjson_client instead (based on a configuration setting) so that once redeployed it wil use the new backend.

**Comment by StephenCoady** [comment]
FYI @ryanlerch

**Comment by ryanlerch** [comment]
PR over on Pagure here:

https://pagure.io/elections/pull-request/89
