### ISSUE TITLE
The fedora infrastructure ansible repo needs to be updated to use the new API

### ISSUE THREAD

**Issue by StephenCoady** [fedora-infra/fasjson#65]
https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/batcave/files/retrieve-security-question.py

https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/batcave/files/sync-openshift-keys.py

There are multiple places within the ansible repo where configs will need to be updated also. Most apps have some config defined there.

Acceptance criteria:

* Every app defined in this epic needs to have its configuration updated
* Configuration should be uniform across all applications
* The PR should be merged with peer-review
* All files within the ansible repo which use the fas2 account system should also be updated.

**Comment by nphilipp** [comment]
Ansible moved to Pagure, these links work:

* https://pagure.io/fedora-infra/ansible/blob/master/f/roles/batcave/files/retrieve-security-question.py
* https://pagure.io/fedora-infra/ansible/blob/master/f/roles/batcave/files/sync-openshift-keys.py

**Comment by ryanlerch** [comment]
I think we can safely ignore https://pagure.io/fedora-infra/ansible/blob/master/f/roles/batcave/files/retrieve-security-question.py since it wont be needed in a post-FAS world

**Comment by ryanlerch** [comment]
So [retrieve-security-question.py](https://pagure.io/fedora-infra/ansible/blob/master/f/roles/batcave/files/retrieve-security-question.py) will actually no longer be needed after the move to Noggin / FreeIPA, so here is the PR to remove it: https://pagure.io/fedora-infra/ansible/pull-request/169

And the other script, [sync-openshift-keys.py](https://pagure.io/fedora-infra/ansible/blob/master/f/roles/batcave/files/sync-openshift-keys.py) was actually already deprecated and removed from batcave, just not deleted from the files directory in ansible, so here is the PR to remove it: https://pagure.io/fedora-infra/ansible/pull-request/168

**Comment by ryanlerch** [comment]
https://pagure.io/fedora-infra/ansible/pull-request/168 is merged. 

The only other one that isnt is https://pagure.io/fedora-infra/ansible/pull-request/169 because this removes a script that might be used until FAS is decomissioned. IMHO this one is basically done, we just need to merge PR169 afterwards. (it really is just cleanup, so we can close this one as fixed IMHO)
