### ISSUE TITLE
pagure distgit needs to be updated to use the new API

### ISSUE THREAD

**Issue by StephenCoady** [fedora-infra/fasjson#68]
the ansible playbook here: https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/distgit/pagure/files/fas2.py creates the requests to contact FAS, these will need to be updated.

this possibly needs to be consolidated with python-fedora once that update happens.

**Comment by pypingou** [comment]
That's no longer used

**Comment by StephenCoady** [comment]
Great, thanks!
