### ISSUE TITLE
membership-map needs to be updated to use the new API

### ISSUE THREAD

**Issue by StephenCoady** [fedora-infra/fasjson#69]
membership-map.py and membership-mwclient.py here: https://pagure.io/fedora-infra/ansible/blob/master/f/roles/membership-map/build/templates both use python-fedora to communicate with FAS.

**Comment by ryanlerch** [comment]
Just wondering if anyone knows the status of these scripts. Both seem to not be working (and unmaintained) for multiple years currently. So not sure if it's worth us having to fix the current issues to then port to the noggin.

# membership-mwclient.py

this script is supposed to generate this wikipage: https://fedoraproject.org/wiki/Ambassadors/MembershipService/Verification but that page has been edited to state that the script has not worked for 3 years.

# membership-map.py

Is supposed to generate data for this page: https://fedoraproject.org/membership-map/ambassadors.html but the map has multiple errors with the JS, and isnt showing anything on the map.
