### ISSUE TITLE
As a user I want a consistant and stable API so that I can use it in my application

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fasjson#7]
This should be based on the investigation in #6.

Acceptance criteria:
- API works
- API supports pagination where it is relevant
- API follows a standard kind of schema
- Schema is published
- Documentation is available to describe how to use the API (including examples)

DoD:
- All AC are met
- Unit tests are written
- Coverage is 100% (or less if justified)
- Code passes the bandit security analyser
- Dependencies are checked for compatible licenses
- Code is formatted according to the Black tool

**Comment by sfinn85** [comment]
Hi @odra 
I pulled these issues into the "in- progress" lane. If the 7 user stories created cover everything that needs to be done to complete this user story. We can possibility delete this. What are your thoughts?

**Comment by odra** [comment]
All issues were solved so I am closing this one.
