### ISSUE TITLE
As a user I want a python library that maps the API into convenient Python objects so I can easily use the API

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fasjson#8]
A python library would be most useful, it would be based on the work in #7 and could take advantage of the schema that the API publishes.

AC:
- The library works and maps API objects to Python objects
- The library is published to PyPI
- Documentation exists to explain how to use the library

DoD:
- All AC are met
- Unit tests are written
- Coverage is 100% (unless properly justified)
- Code passes the bandit security analyser
- Dependencies are checked for compatible licenses
- Code is formatted according to the Black tool

**Comment by odra** [comment]
I think we could use some openapi spec code generating tool for this.

@abompard I could look at this one if that's ok

**Comment by abompard** [comment]
Yep that sounds like an excellent option.

**Comment by abompard** [comment]
@abompard to create a new repository for the client

**Comment by abompard** [comment]
See https://github.com/fedora-infra/fasjson-client
