### ISSUE TITLE
As a user I would like the ability to search for other users based on their email, nick etc.

### ISSUE THREAD

**Issue by StephenCoady** [fedora-infra/fasjson#89]
## Acceptance Criteria

* A search endpoint is available on FASJson
* Any value can be passed and it will match against multiple fields
* Multiple users can be returned for one search

## Definition of Done

* all of the above are complete
* testing
* documentation

**Comment by tiran** [comment]
Two quick notes:
* all fields must be indexed
* IPA let's you configure seacrch fields with ``ipa config-mod`` / ``ipaUserSearchFields`` attribute in ``cn=ipaConfig,cn=etc,$REALM``

```
$ ipa config-show
  User search fields: uid,givenname,sn,telephonenumber,ou,title
  Group search fields: cn,description
```

**Comment by tiran** [comment]
```
$ ipa user-mod fasuser1 --fasircnick=myircnick
$ ipa user-find myircnick
---------------
0 users matched
---------------
----------------------------
Number of entries returned 0
----------------------------
```

Update search fields. IPA verifies that search fields apply to users, so we need to add ``fasuser`` to default object classes for users:

```
$ ipa config-mod --userobjectclasses={top,person,organizationalperson,inetorgperson,inetuser,posixaccount,krbprincipalaux,krbticketpolicyaux,ipaobject,ipasshuser,fasuser}
$ ipa config-mod --usersearch="uid,givenname,sn,telephonenumber,ou,title,fasircnick"
```

Search again
```
$ipa user-find myircnick
--------------
1 user matched
--------------
  User login: fasuser1
  First name: User1
  Last name: Demo
  Home directory: /home/fasuser1
  Login shell: /bin/sh
  Principal name: fasuser1@FAS.EXAMPLE
  Principal alias: fasuser1@FAS.EXAMPLE
  Email address: fasuser1@fas.example
  UID: 240000003
  GID: 240000003
  Account disabled: False
----------------------------
Number of entries returned 1
```

The field is indexed by ``cn=fasIRCNick,cn=index,cn=userRoot,cn=ldbm database,cn=plugins,cn=config``.

**Comment by StephenCoady** [comment]
Thats great @tiran. Thanks very much for that, will save me a lot of time.

**Comment by StephenCoady** [comment]
@tiran am I correct in saying these lines in freeipa-fas do the same thing?

https://github.com/fedora-infra/freeipa-fas/blob/master/updates/99-fas.update#L38-L45

**Comment by tiran** [comment]
> @tiran am I correct in saying these lines in freeipa-fas do the same thing?
> 
> [fedora-infra/freeipa-fas:updates/99-fas.update@`master`#L38-L45](https://github.com/fedora-infra/freeipa-fas/blob/master/updates/99-fas.update?rgh-link-date=2020-06-09T13%3A57%3A07Z#L38-L45)

These lines create the database index to make searching over fasIRCNick more efficient.

The ``ipa config-mod`` lines modify the search filters that are used by ``ipa user-find``. The command ``ipa user-find myircnick`` performs a kind of full text search on multiple attributes. The resulting query filter is ``filter="(&(|(uid=*myircnick*)(givenName=*myircnick*)(sn=*myircnick*)(telephoneNumber=*myircnick*)(ou=*myircnick*)(title=*myircnick*)(fasIRCNick=*myircnick*))(objectClass=posixaccount))"``

**Comment by abompard** [comment]
> Update search fields. IPA verifies that search fields apply to users, so we need to add `fasuser` to default object classes for users:

Is this the sort of config change that can be done in `freeipa-fas/update/89-fas.update`?
