### ISSUE TITLE
As a developer I want an comprehensive list of applications that make queries to FAS so that I can port them to the new API

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fasjson#9]
A good first step would be to look into the infra Ansible repo for the `fedoraDummyUserPassword` variable, it means that this app is using the dummy FAS account to make queries.

Another way would be to grep all our source codes for the `fedoraproject.org/accounts` URL.

Once we have the list we need to look at what those apps do in their FAS queries. Whether it's read-only or not, what endpoints they are querying, etc.

AC:
- There is a comprehensive list of apps that talk to FAS
- For each app the list details which endpoint / which query is made
- We mainly needs the apps that do read-only access but those who do read-write access should be flagged for later.
- The source code / repo and points of contacts are identified
- Code owners of those apps know that a code change will be necessary when the project is deployed, and they know that we are willing to do it or to assist them doing it.

DoD: All AC are met

**Comment by abompard** [comment]
Can you look at that @amoloney1 please? Thanks :-)

**Comment by abompard** [comment]
Clément came up with a preliminary app list: https://hackmd.io/oX8Ks2FvR4CgNmhArfd2QQ

**Comment by StephenCoady** [comment]
Thats great, thanks @abompard & @cverna. I think there might be some more so I will put them all together and then use that to make a plan with the codeowners if possible.

**Comment by bkmgit** [comment]
Is the hackmd list the authoritative one?

**Comment by StephenCoady** [comment]
@bkmgit no, this project's wiki has some more [1]. Its a bit rough so I will be creating individual issues shortly to list them by app/project and taking it from there. any feedback you have is welcome.

[1] https://github.com/fedora-infra/fasjson/wiki

**Comment by bkmgit** [comment]
Would be helpful to add nuancier https://github.com/fedora-infra/nuancier

**Comment by StephenCoady** [comment]
@bkmgit can you point me to where nuancier uses FAS currently? Maybe I missed it when I looked first.

**Comment by bkmgit** [comment]
See https://github.com/fedora-infra/nuancier/blob/master/nuancier/__init__.py 
Am working on porting this to OIDC, though if this will be available soon, then would like to use it directly instead.
