### ISSUE TITLE
The packager-bugzilla-sync toddler plugin needs to be updated to use FASJSON

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fasjson#99]
~~https://pagure.io/Fedora-Infra/packager-sync-bz~~  
https://pagure.io/fedora-infra/toddlers/blob/master/f/toddlers/plugins/packager_bugzilla_sync.py

It uses `person_by_username` and `group_by_name`: https://pagure.io/fedora-infra/packager-sync-bz/blob/master/f/packager_sync_bz/fedora_account.py

**Comment by pypingou** [comment]
This is being ported to toddlers

**Comment by ryanlerch** [comment]
@pypingou so can we close this one here then?

**Comment by pypingou** [comment]
Probably not, we could just open a ticket for toddler and close this one :)

**Comment by pypingou** [comment]
Note: this one has already been ported to toddlers

**Comment by StephenCoady** [comment]
PR for review: https://pagure.io/fedora-infra/toddlers/pull-request/57
